DATASET: 'scannet'
BATCH_SIZE: 2
SAVE_SCENE_MESH: False
LOGDIR: './checkpoints_base_new'
SAVE_FREQ: 1
MODE: 'train'
RESUME: True 
LOADCKPT: 'checkpoints_base_new/model_000004.ckpt'  
# checkpoints_base_new/model_000004.ckpt  |  checkpoints_hard/model_000002.ckpt  |  checkpoints_base_new_hard_composite_base/model_000002.ckpt  |  checkpoints_base_new_hard_composite_hard/model_000001.ckpt

TRAIN:
  PATH: 'datasets/scannet'
  EPOCHS: 50
  N_VIEWS: 9
  LR: 0.001
  N_WORKERS: 16  # 64 for training, 16 for testing
  LREPOCHS: '6,8,10:2'

TEST:
  PATH: 'datasets/scannet'
  N_VIEWS: 9
  N_WORKERS: 8

MODEL:
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]
  GROUNDING_IMG_IDX: 4

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True

  LW: [1.0, 0.8, 0.64]

  THRESHOLDS: [0, 0, 0]
  POS_WEIGHT: 1.5

  SELECTED_IMG_IDS: [0, 3, 6]
  